name: Kiosk Scene
version: "0.10.45"
slug: kiosk_scene
description: Хостинг kiosk-scene как отдельного add-on Home Assistant.
url: https://github.com/WeLizard/kiosk-scene
arch:
  - amd64
  - aarch64
  - armv7
startup: services
boot: auto
init: false
hassio_api: false
homeassistant_api: true
host_network: true
ingress: true
ingress_port: 48123
panel_title: Kiosk Scene
panel_icon: mdi:monitor-dashboard
map:
  - config:rw
options:
  timezone: "Europe/Sofia"
  active_pack_id: "neiri"
schema:
  timezone: str?
  active_pack_id: str?
